
INSERT INTO USERS VALUES('user', '123', true);
INSERT INTO AUTHORITIES VALUES('user', 'USER_ROLE');

INSERT INTO USERS VALUES('carmelo', '010101', true);
INSERT INTO AUTHORITIES VALUES('carmelo', 'ADMIN_ROLE');
INSERT INTO AUTHORITIES VALUES('carmelo', 'USER_ROLE');

/*
INSERT INTO USUARIOS VALUES('user', '123', 'user@correo.com');
INSERT INTO AUTHORITIES VALUES('user', 'USER_ROLE');

INSERT INTO USUARIOS VALUES('carmelo', '010101', 'carmelo@tutor.com');
INSERT INTO AUTHORITIES VALUES('carmelo', 'ADMIN_ROLE');
INSERT INTO AUTHORITIES VALUES('carmelo', 'USER_ROLE');
*/

COMMIT;
